"""Noise filters for call graph generation."""

NOISE_METHOD_NAMES = {
    "print",
    "println",
    "printf",
    "hashCode",
    "equals",
    "toString",
    "getClass",
    "notify",
    "notifyAll",
    "wait",
    "clone",
    "finalize",
    "compareTo",
    "isEmpty",
    "size",
    "length",
    "stream",
    "parallelStream",
    "forEach",
    "map",
    "filter",
    "collect",
    "orElse",
    "orElseGet",
    "add",
    "append",
    "remove",
    "contains",
    "log",
    "debug",
    "info",
    "warn",
    "error",
}
